### ISSUE TITLE
How long does it take for my stake to appear on the dahboard.

### ISSUE THREAD

**Issue by gerardbartlett** [TheGPooL/Guides#3]
I staked (delegated) over 20,000 yesterday and am still waiting for it to appear on the dashboard . my wallet shows that it is being held but nothing has happened yet on my Gpool page. I am getting slightly anxious.

**Comment by Atherrien** [comment]
I am seeing the same thing. I staked 10,600 coins like 4 or 5 days ago. I think I am getting deposits in my account but it is not showing up on the dashboard. It doesnt even say I am in Guardian Nodes etc. Hoping to understand the bigger picture here a bit better. The lack of tracking does make me nervous.

**Comment by TheGPooL** [comment]
Everything that happens in Crypto happens on the Blockchain, you should be tracking everything your doing on the Theta Blockchain through the Official Theta Blockchain Explorer linked here (https://explorer.thetatoken.org). We know there has been a lot of new comers to Crypto lately so we are adding tracking on GPooL as well. However please keep in mind the standard should always be to default to the Official Blockchain Explorer, this goes for any project out there.

**Comment by Atherrien** [comment]
Yeah, that’s not what we are asking...

**Comment by TheGPooL** [comment]
Your asking why a website that was built with a dashboard to track Theta that was **held in cold storage wallets called "Staking on GPooL"** (which is no longer a service we provide) is not showing information about something you did on the Theta blockchain, **Delegated** (different then "stacking on GPooL"). The reason for the Dashboard was to provide information to "stakers" that could not find that information on the blockchain, Delegators always could but we had to build a tool for "stakers".   The answer was, this is because this was not something you did on the website. You interacted with the Blockchain (this is called Delegation) and has nothing to do with the website tracking right this second. As I stated above we are now adding a copy of tracking on the GPooL website. Please know all that means is we are taking this same info you can see right now on the blockchain and we are going to show it on GPooL as well. As stated please always default to the Official Blockchain Explorer, this goes for any project out there. Delegation happens 100% in your wallet, while interacting with the Theta blockchain. GPooL and the dashboard will just be taking the information publicly available already on the explorer and showing it now in a second place

**Comment by Dao-Enlightenment** [comment]
I figured it out. Hope this help everyone.  For most of us that are new and still learning. 

Step 1. Go to Dashboard
Step 2. Scroll down to Claim Your Delegated Address
Step 3. Enter your Theta Address that you own.  Then click CLAIM
Step 4. Follow the instruction on the next page.  They will ask you to send some TFuel to the address
Step 5. Reload Dashboard page and all your rewards and info should show up there.

You only need to claim your address ownership once so they have your info.

Theta to the MOON !!!

**Comment by avatarsatosh** [comment]
> 
> 
> I staked (delegated) over 20,000 yesterday and am still waiting for it to appear on the dashboard . my wallet shows that it is being held but nothing has happened yet on my Gpool page. I am getting slightly anxious.

i had similar issues not until i texted the customer service via telegram on https://t.me/thetacustomerservice to get my dashboard error fixed, avoid multiple activities on theta wallet mate and text the customer service .
